<%@page pageEncoding="MS949" %>
<option value="techtrend">TECH TREND</option>
<option value="lecture">강좌</option>
<option value="TOOL">개발툴</option>
<option value="TOOLqna">개발툴 QnA</option>
<option value="ajax">Ajax</option>
<option value="ajaxqna">Ajax QnA</option>
<option value="bbs2">DB Tips</option>
<option value="bbs1">DB QnA</option>
<option value="bbs4">JSP Tips</option>
<option value="bbs3">JSP QnA</option>
<option value="weblogic">j2ee Tips</option>
<option value="weblgqna">j2ee QnA</option>
<option value="xmltip">XML Tips</option>
<option value="xmlqna">XML QnA</option>
<option value="ruby">Ruby on Rails</option>
<option value="rubyqna">Ruby on Rails QnA</option>
<option value="flex">Flex</option>
<option value="flexqna">Flex QnA</option>
<option value="bbs7">소스자료실</option>
<option value="docs">문서자료실</option>
<option value="etc">기타자료실</option>
<option value="bbs6">사는 얘기</option>
<option value="japanlife">일본사는얘기</option>
<option value="bbs5">머리식히는 곳</option>
<option value="movie">movie story</option>
<option value="howmuch">얼마면돼</option>
<option value="lifeqna">의견좀...</option>
<option value="news">뉴스따라잡기</option>
<option value="solo">싱글의 미학</option>
<option value="recruit">구인/구직/홍보</option>
<option value="engdocs">english bbs</option>
<option value="krtomcat">번역</option>
<option value="link">추천사이트</option>
<option value="goodjob">좋은회사</option>
<option value="market">장터</option>
<option value="model2jsp">모델2JSP책관련</option>
<option value="notice">공지사항</option>
<option value="okboard">자료실문답</option>
<option value="useful">유용한 정보</option>
<option value="mac">맥 정보</option>
<option value="ihaveadream">정부는 개발자를 위해</option>
<option value="javastudy">프로그램기초스터디</option>
<option value="ns">자바패턴1기</option>
<option value="dbstudy">DB스터디</option>
<option value="springstudy">스프링 스터디</option>
<option value="xf">SLF</option>
<option value="twitter">트위터</option>
<option value="trash">짬통</option>
