<%@page pageEncoding="utf-8"%>
<option value="cooper">협동조합준비위</option>
<option value="book">책 얘기</option>
<option value="recruit">구인/구직</option>
<option value="pr">홍보</option>
<option value="institute">학원</option>
<option value="html5">HTML5</option>
<option value="android">안드로이드</option>
<option value="techtrend">TECH TREND</option>
<option value="TOOL">개발툴</option>
<option value="TOOLqna">개발툴 QnA</option>
<option value="ajax">JavaScript</option>
<option value="ajaxqna">JavaScript QnA</option>
<option value="bbs6">사는 얘기</option>
<option value="howmuch">얼마면돼</option>
<option value="lifeqna">토론/기타 QnA</option>
<option value="news">뉴스따라잡기</option>
<option value="critical">정치 얘기</option>
<option value="lecture">강좌</option>
<option value="solo">싱글의 미학</option>
<option value="bbs5">머리식히는 곳</option>
<option value="bbs2">DB Tips</option>
<option value="bbs1">DB QnA</option>
<option value="bbs4">JAVA/JSP Tips</option>
<option value="bbs3">JAVA/JSP QnA</option>
<option value="weblogic">j2ee Tips</option>
<option value="weblgqna">j2ee QnA</option>
<option value="mac">맥 정보</option>
<option value="useful">유용한 정보</option>
<option value="ihaveadream">정부는 개발자를 위해</option>
<%
	Boolean hideIt = (Boolean)request.getAttribute("hideIt");
	if (hideIt == null || !hideIt) {
%><option value="notice">공지사항</option>
<%
	}
%><option value="link">추천사이트</option>
<option value="goodjob">좋은회사</option>
<option value="market">장터</option>
<option value="movie">movie story</option>
<option value="xmltip">XML Tips</option>
<option value="xmlqna">XML QnA</option>
<option value="bbs7">소스자료실</option>
<option value="docs">문서자료실</option>
<option value="etc">기타자료실</option>
<option value="krtomcat">번역</option>
<option value="okboard">자료실문답</option>
<option value="javastudy">프로그램기초스터디</option>
<option value="springstudy">스프링 스터디</option>
<option value="dbstudy">DB스터디</option>
<option value="engdocs">english bbs</option>
<option value="model2jsp">모델2JSP책관련</option>
<option value="ruby">Ruby on Rails</option>
<option value="rubyqna">Ruby on Rails QnA</option>
<option value="flex">Flex</option>
<option value="flexqna">Flex QnA</option>
<option value="japanlife">일본사는얘기</option>
<option value="twitter">트위터</option>
<option value="trash">짬통</option>
<%--<option value="iphone">iOS</option>--%>
<%--<option value="xf">SLF</option> --%>
<%--<option value="ns">자바패턴1기</option>--%>
